version: "3.8"
services:
  currency:
    container_name: currency
    build: ./currency
    volumes:
      - ./currency:/app
    depends_on:
      mysql: 
        condition: service_started
    restart: always
    ports:
      - "8000:8000"
    environment: 
      PHP_FPM_PUID: 1000
      PHP_FPM_PGID: 1000
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql:delegated
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: currency
    restart: always
volumes:
  mysql_data: